### ISSUE TITLE
bug: After closing the viewer I get a white screen

### ISSUE THREAD

**Issue by dylanvdmerwe** [sitewaerts/cordova-plugin-document-viewer#45]
On iOS, I can open the PDFs perfectly. They work very well. However as soon as you press the "Done" button and the viewer closes, a white screen is shown. The app then needs to be restarted as it is completely unresponsive. 

There is nothing exciting logged from XCode:
```
2017-02-03 09:10:54.357774 Cochrane[358:86690] [pdfviewer] path: /var/containers/Bundle/Application/AE8CD45C-D181-45CC-8C08-306316A831AE/Cochrane.app/www/assets/documents/DefenceTesting/ASTMTESTREPORT.pdf
2017-02-03 09:10:54.369403 Cochrane[358:86690] THREAD WARNING: ['SitewaertsDocumentViewer'] took '12.610107' ms. Plugin should use a background thread.
2017-02-03 09:10:54.375280 Cochrane[358:86690] [pdfviewer] path: /var/containers/Bundle/Application/AE8CD45C-D181-45CC-8C08-306316A831AE/Cochrane.app/www/assets/documents/DefenceTesting/ASTMTESTREPORT.pdf
2017-02-03 09:10:54.378042 Cochrane[358:86690] [pdfviewer] options: {
    android =     {
        viewerAppActivity = DocumentViewerActivity;
        viewerAppPackage = "de.sitewaerts.cleverdox.viewer";
    };
    bookmarks =     {
        enabled = 0;
    };
    documentView =     {
        closeLabel = Done;
    };
    email =     {
        enabled = 0;
    };
    navigationView =     {
        closeLabel = Back;
    };
    openWith =     {
        enabled = 0;
    };
    print =     {
        enabled = 0;
    };
    search =     {
        enabled = 0;
    };
    title = "ASTMTESTREPORT.pdf";
}
2017-02-03 09:10:54.398381 Cochrane[358:86690] [pdfviewer] toolbar-options: {
    android =     {
        viewerAppActivity = DocumentViewerActivity;
        viewerAppPackage = "de.sitewaerts.cleverdox.viewer";
    };
    bookmarks =     {
        enabled = 0;
    };
    documentView =     {
        closeLabel = Done;
    };
    email =     {
        enabled = 0;
    };
    navigationView =     {
        closeLabel = Back;
    };
    openWith =     {
        enabled = 0;
    };
    print =     {
        enabled = 0;
    };
    search =     {
        enabled = 0;
    };
    title = "ASTMTESTREPORT.pdf";
}
2017-02-03 09:10:54.399673 Cochrane[358:86690] [pdfviewer] toolbar-options close label: Done
2017-02-03 09:10:54.438858 Cochrane[358:86690] [pdfviewer] toolbar-options bookmarks: 0
2017-02-03 09:10:54.439071 Cochrane[358:86690] [pdfviewer] toolbar-options email: 0
2017-02-03 09:10:54.439173 Cochrane[358:86690] [pdfviewer] toolbar-options print: 0
2017-02-03 09:10:54.439268 Cochrane[358:86690] [pdfviewer] toolbar-options open with: 0
2017-02-03 09:10:54.541323 Cochrane[358:86690] [pdfviewer] toolbar-options title label: ASTMTESTREPORT.pdf
2017-02-03 09:10:54.551400 Cochrane[358:86690] THREAD WARNING: ['SitewaertsDocumentViewer'] took '176.719238' ms. Plugin should use a background thread.
```

More information:
Can reproduce on iOS 10.2 Simulator
Can reproduce on iOS 10.2 iPad device
Can reproduce on iOS 9.3 iPad device

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by dylanvdmerwe** [comment]
![white screen](https://cloud.githubusercontent.com/assets/2852839/22583028/195a0094-e9f3-11e6-91eb-d94f5f5be31b.gif)


The app is still showing in the DOM, but something is in front of everything.

Version 0.8.0

**Comment by regnete** [comment]
Perfect bug report! Thx.

We exeprienced something similar (see https://github.com/sitewaerts/cordova-plugin-document-viewer/issues/36) which was fixed in 0.8.0.

Are you using the cordova status bar plugin in your app?
Are you able to reproduce the issue with our sample app?

**Comment by dylanvdmerwe** [comment]
My list of plugins:
```
cordova-fabric-plugin 1.1.3 "cordova-fabric-plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-document-viewer 0.5.0 "SitewaertsDocumentViewer"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-nativeaudio 3.0.7 "Cordova Native Audio"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 1.5.3 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

The white layer that sits in front of the app after dismissing a PDF is baffling me. It's like something has not closed properly. I can't inspect it through Safari or anything either - but the rest of the app is still in the DOM.

**Comment by regnete** [comment]
cordova-plugin-document-viewer 0.5.0 "SitewaertsDocumentViewer" ?
Please ensure you are using 0.8.0.

**Comment by dylanvdmerwe** [comment]
Weird, I was pulling directly from github: `<plugin name="cordova-plugin-document-viewer" spec="https://github.com/sitewaerts/cordova-plugin-document-viewer" />`

Anyway I made sure 0.8.0 is installed. 

`cordova-plugin-document-viewer 0.8.0 "SitewaertsDocumentViewer"`

Still shows me a white screen after dismissing the PDF.

**Comment by regnete** [comment]
Are you able to reproduce the issue with our sample app?

Are you able to reproduce the issue without status bar plugin installed, or with 2.2.0 of status bar plugin?
We are currently using cordova-plugin-statusbar 2.2.0 "StatusBar", which works perfect with 0.8.0. May be the issue is triggered by cordova-plugin-statusbar 2.2.1?

**Comment by dylanvdmerwe** [comment]
Good call! I reverted back to `cordova-plugin-statusbar@2.2.0` and the issue is fixed.

**Comment by regnete** [comment]
Great. Thats what I call a productive cup of coffe. I'll get the next one now.

I already filed ab bug report focusing this issue in December. Have a look at https://github.com/apache/cordova-plugin-statusbar/commit/a120ba1a1ffb27d46f2ac7962648e6f8a7a5b24c and https://issues.apache.org/jira/browse/CB-12196

I think it will be fixed 2.2.2.

Currently we use the dev version directly from github (https://github.com/apache/cordova-plugin-statusbar). With that version the issue you described is gone.

They had several issues with "white screen" after interacting with a native plugin (e.g. camera, document-viewer). I guess they calculate a wrong height and position for the cordova viewport after closing a native component. Thats why you cannot "see" the white layer in your dom debuger. It's probably not a html element but a native component.
